name: generate

on:
  schedule:
      - cron: '0 0/1 * * *'
  workflow_dispatch:

jobs:
  dump:
    runs-on: windows-latest

    env:
      VERSION_KEY: game-data-version
      VERSION_FILENAME: version_key.json
      MASTER_FILENAME: master.zip

    steps:
    - uses: actions/checkout@v2
      with:
        repository: karanokk/FGODumper
        token: ${{ secrets.PRIVATE_REPO_PAT }}

    - name: Cache game data version
      uses: actions/cache@v2
      with:
        path: ${{ env.VERSION_FILENAME }}
        key: ${{ runner.os }}-${{ env.VERSION_KEY }}

    - name: Build & run FGODumper
      id: product
      run: |
        nuget restore FGODumper.sln
        dotnet build --configuration Release FGODumper

        & '.\FGODumper\bin\Release\FGODumper.exe' ${{ env.VERSION_FILENAME }}

        $masterPath = 'master.json'
        $isUpdated = Test-Path $masterPath
        echo "::set-output name=isUpdated::${isUpdated}"
        if ($isUpdated) {
          Compress-Archive -Path $masterPath -DestinationPath ${{ env.MASTER_FILENAME}}

          $versionJson = (Get-Content ${{ env.VERSION_FILENAME }}) | ConvertFrom-Json
          $dateVer = $versionJson.dateVer;
          $updatedAt = (Get-Date '01-01-1970 00:00:00').AddSeconds($dateVer +9*3600)
          $updatedAt = Get-Date $updatedAt -UFormat '%B %d, %Y %R'
          echo "::set-output name=ver::${dateVer}";
          echo "::set-output name=updatedAt::${updatedAt}";
        }
      shell: powershell
    
    - name: Create Release
      if: steps.product.outputs.isUpdated == 'True'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.product.outputs.ver }}
        release_name: MasterData ${{ steps.product.outputs.ver }}
        body: |
          Updated on ${{ steps.product.outputs.updatedAt }} UTC+9
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: steps.product.outputs.isUpdated == 'True'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.MASTER_FILENAME }}
        asset_name: ${{ env.MASTER_FILENAME }}
        asset_content_type: application/zip
